# Generated by Django 3.1 on 2020-09-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='thubnail',
            new_name='thumbnail',
        ),
    ]
